---
- name: Install Docker Compose V2 plugin
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present
  become: true

- name: Launch Wazuh Docker stack with Compose V2
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_compose_dir }}"
    state: present
  become: true
