---
- name: Deploy Wazuh Docker single node with Cloudflare certificate
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - cdocker.docker_compose_v2

  roles:
    - clone_wazuh_docker
    - configure_cert
    - deploy
