---
- name: Deploy Wazuh Docker single node with HTTPS
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - community.docker
    - community.crypto

  roles:
    - clone_wazuh_docker
    - configure_cert
    - deploy
