---
- name: Ensure cert directory exists
  ansible.builtin.file:
    path: "{{ cert_dest_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- block:
    - name: Generate private key for self-signed cert
      community.crypto.openssl_privatekey:
        path: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        size: "{{ self_signed.key_size }}"
        type: RSA
        mode: '0600'

    - name: Generate self-signed dashboard certificate
      community.crypto.x509_certificate:
        path: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
        privatekey_path: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        provider: selfsigned

        # validity window
        selfsigned_not_before: "now"
        selfsigned_not_after: "{{ lookup('pipe', 'date -d \"+' + self_signed.cert_validity_days|string + ' days\" -Iseconds') }}"

        # X.509 v3 and digest
        selfsigned_version: 3
        selfsigned_digest: sha256

        # Distinguished Name attributes
        attributes:
          commonName:            "{{ self_signed.common_name }}"
          countryName:           "{{ self_signed.country }}"
          stateOrProvinceName:   "{{ self_signed.state }}"
          localityName:          "{{ self_signed.locality }}"
          organizationName:      "{{ self_signed.organization }}"
          organizationalUnitName: "{{ self_signed.organizational_unit }}"
        mode: '0644'
  when: use_self_signed_cert | bool
  delegate_to: localhost
  run_once: true

- block:
    - name: Deploy Cloudflare Origin CA cert
      ansible.builtin.copy:
        src: origin.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
        mode: '0644'

    - name: Deploy Cloudflare Origin CA key
      ansible.builtin.copy:
        src: origin-key.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        mode: '0600'
  when: not use_self_signed_cert | bool
  delegate_to: localhost
  run_once: true

- name: Generate internal indexer & manager certificates if missing
  ansible.builtin.command:
    cmd: docker-compose -f generate-indexer-certs.yml run --rm generator
    chdir: "{{ wazuh_compose_dir }}"
  args:
    creates: "{{ cert_dest_dir }}/root-ca.pem"
  run_once: true
