---
- name: Create certificate directory
  ansible.builtin.file:
    path: "{{ cert_dest_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Cloudflare Origin CA certificate
  ansible.builtin.copy:
    src: origin.pem
    dest: "{{ cert_dest_dir }}/origin.pem"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Deploy Cloudflare Origin CA private key
  ansible.builtin.copy:
    src: origin-key.pem
    dest: "{{ cert_dest_dir }}/origin-key.pem"
    mode: '0600'
  delegate_to: localhost
  run_once: true

