---
- name: Generate internal indexer & manager certificates
  ansible.builtin.command:
    cmd: docker-compose -f generate-indexer-certs.yml run --rm generator
    chdir: "{{ wazuh_compose_dir }}"
  args:
    creates: "{{ cert_dest_dir }}/root-ca.pem"
  run_once: true

- name: Deploy Cloudflare dashboard certificate
  ansible.builtin.copy:
    src: origin.pem
    dest: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Deploy Cloudflare dashboard private key
  ansible.builtin.copy:
    src: origin-key.pem
    dest: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
    mode: '0600'
  delegate_to: localhost
  run_once: true
