---
- name: Ensure cert directory exists
  ansible.builtin.file:
    path: "{{ cert_dest_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Generate private key for self-signed cert
  ansible.builtin.command: >
    openssl genpkey
      -algorithm RSA
      -out "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
      -pkeyopt rsa_keygen_bits:{{ self_signed.key_size }}
  args:
    creates: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
  delegate_to: localhost
  run_once: true

- name: Generate self-signed dashboard certificate
  ansible.builtin.command: >
    openssl req -x509 -new -nodes
      -key "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
      -sha256
      -days {{ self_signed.cert_validity_days }}
      -out "{{ cert_dest_dir }}/wazuh.dashboard.pem"
      -subj "/C={{ self_signed.country }}/ST={{ self_signed.state }}/L={{ self_signed.locality }}/O={{ self_signed.organization }}/OU={{ self_signed.organizational_unit }}/CN={{ self_signed.common_name }}"
  args:
    creates: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
  delegate_to: localhost
  run_once: true

- block:
    - name: Deploy Cloudflare Origin CA cert
      ansible.builtin.copy:
        src: origin.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Cloudflare Origin CA key
      ansible.builtin.copy:
        src: origin-key.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        owner: root
        group: root
        mode: '0600'
  when: not use_self_signed_cert | bool
  delegate_to: localhost
  run_once: true

- name: Generate internal indexer & manager certificates if missing
  ansible.builtin.command:
    cmd: docker-compose -f generate-indexer-certs.yml run --rm generator
    chdir: "{{ wazuh_compose_dir }}"
  args:
    creates: "{{ cert_dest_dir }}/root-ca.pem"
  delegate_to: localhost
  run_once: true
