---
- name: Ensure cert directory exists
  file:
    path: "{{ cert_dest_dir }}"
    state: directory
    mode: '0755'

- block:
    - name: Generate private key for self-signed cert
      community.crypto.openssl_privatekey:
        path: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        size: "{{ self_signed.key_size }}"
        type: RSA
        mode: '0600'

    - name: Generate self-signed certificate
      community.crypto.x509_certificate:
        path: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
        privatekey_path: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        csr_common_name: "{{ self_signed.common_name }}"
        provider: selfsigned
        days: "{{ self_signed.cert_validity_days }}"
        subject:
          countryName: "{{ self_signed.country }}"
          stateOrProvinceName: "{{ self_signed.state }}"
          localityName: "{{ self_signed.locality }}"
          organizationName: "{{ self_signed.organization }}"
          organizationalUnitName: "{{ self_signed.organizational_unit }}"
        mode: '0644'

  when: use_self_signed_cert | bool
  delegate_to: localhost
  run_once: true

- block:
    - name: Deploy Cloudflare Origin CA cert
      copy:
        src: origin.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard.pem"
        mode: '0644'

    - name: Deploy Cloudflare Origin CA key
      copy:
        src: origin-key.pem
        dest: "{{ cert_dest_dir }}/wazuh.dashboard-key.pem"
        mode: '0600'

  when: not use_self_signed_cert | bool
  delegate_to: localhost
  run_once: true

- name: Generate internal indexer certs if missing
  command: docker-compose -f generate-indexer-certs.yml run --rm generator
  args:
    chdir: "{{ wazuh_compose_dir }}"
    creates: "{{ cert_dest_dir }}/root-ca.pem"
  run_once: true

